### ISSUE TITLE
New geometry setup

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#70] opened 2016-04-07 20:47 UTC
@lstagner @bgrierson21  Previously for the 330lt beams on DIII-D, I/Brian had the geometry as : 

```
origin:[-139.49, 233.77, 0.0]
alpha: -1.46293
beta: 0
gamma: 0
nx,ny,nz: 96,48,50
xmin,xmax:35,95
ymin,ymax:-50,50
zmin,zmax:-70,70

```
For some reason this causes prefida to say: ERROR: Beam centerline does not intersect grid.

This is what you have in run_tests:
```
   ;; Non-rotated, Non-tilted Grid
   grid01 = {nx:50,ny:60,nz:70,$
             xmin:-50.d0,xmax:50.d0,$
             ymin:-230.d0,ymax:-110.d0,$
             zmin:-70.d0,zmax:70.d0,$
             alpha:0.d0,beta:0.d0,gamma:0.d0,$
             origin:[0.d0,0.d0,0.d0]}
```
The obvious differences are the origin, and the symmetry in xmin,xmax. Has something else about the geometry changed between versions? Do you have working examples for any of the DIII-D beams so I can compare?

Thanks

**Comment by lstagner** [comment] 2016-04-07 21:19
The test case are completely made up so they do not reflect any actually machine. They are just used for regression testing so it is not surprising that the beam didn't intersect. 

You will notice that there isn't a `D3D` directory in the repository anymore. I moved all the old device routines into their own repository ([DIII-D](https://github.com/D3DEnergetic/d3d-fidasim) and [NSTX-U](https://github.com/D3DEnergetic/nstx-fidasim)) to separate out the development. This (and prefidas redesign) also allows for maximum flexibility in deciding how FIDASIM runs are done at DIII-D. 

As of now I have been too focused on documentation to get a DIII-D case running but it shouldn't be very difficult to get it up and running. I'll open up an issue on the d3d-fidasim repository to discuss how we want the D3D routines to behave.

**Comment by lstagner** [comment] 2016-04-07 21:33
Issue opened on the DIII-D repository https://github.com/D3DEnergetic/d3d-fidasim/issues/1

**Comment by shaunhaskey** [comment] 2016-04-07 21:50
@lstagner Just to clarify: I get the "beam didn't intersect error" when I use the geometry for the 330lt beam that worked with previous versions of FIDASIM, so I am worried about underlying changes in how the geometry is defined between versions that I need to be aware of. (the test cases don't raise the error).

**Comment by lstagner** [comment] 2016-04-07 22:25
Ok sorry for closing the issue. Its probably best to describe the beam geometry with a picture.
Here is one possible configuration
```fortran
nx =   12    !! Number of cells in X direction (Into Plasma)
ny =   10    !! Number of cells in Y direction
nz =  10    !! Number of cells in Z direction
xmin =   0           !! Minimum X value [cm]
xmax =    60.0    !! Maximum X value [cm]
ymin =   -25.0     !! Minimum Y value [cm]
ymax =    25.0    !! Maximum Y value [cm]
zmin =  -25.0      !! Minimum Z value [cm]
zmax =   25.0     !! Maximum Z value [cm]

!! Tait-Bryan Angles for z-y`-x`` rotation
alpha =   0.00000     !! Rotation about z-axis [rad]
beta  =   0.00000     !! Rotation about y`-axis [rad]
gamma =   0.00000     !! Rotation about x``-axis [rad]

!! Beam Grid origin in machine coordinates (cartesian)
origin(1) =     0.0     !! X value [cm]
origin(2) =     0.0     !! Y value [cm]
origin(3) =     0.0     !! Z value [cm]
```
Will make the following beam grid.

![figure_1](https://cloud.githubusercontent.com/assets/4305891/14368451/95bf441e-fcd2-11e5-95d3-8998263194bc.png)

If I change the Tait-Bryan angles and origin to 
```fortran
alpha = 60*(pi/180.0)
beta = 30*(pi/180.0)
gamma = 0.0
origin = [-50.0,-50.0, 0.0]
```

Then you would get the following

![figure_1-1](https://cloud.githubusercontent.com/assets/4305891/14368453/994c51c6-fcd2-11e5-994b-b7bd2ae045fe.png)

As you can see what happen was first I rotated counter-clockwise about the `z` axis by `alpha` creating a `x' , y' ,z'` system  and then I rotated counter-clockwise about rotated about the `y'` axis creating the `x", y", z"`. If I set gamma I would of then rotated counter-clockwise about the `x"` axis. 

Finally I then moved the box to the `origin`

To get the `alpha` and `beta` angles you can look at the following [prefida code](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/prefida.pro#L693) to calculate them from the neutral beam geometry

**Comment by lstagner** [comment] 2016-04-07 23:01
Looking at what you had it looks like you need to set `alpha = pi + 1.46293` to get the right orientation

**Comment by lstagner** [comment] 2016-04-08 17:58
In #71 I added a IDL routine to calculate the beam grid given the NBI geometry(beam_grid.pro) I would suggest using that.

**Closed by lstagner** 2016-04-08 17:58 UTC

**Comment by shaunhaskey** [comment] 2016-04-09 01:30
I'm still confused.... Please point out if I mess up somewhere along the way:

There are two co-ordinate systems: Machine co-ordinates (u, v, w) and FIDASIM simulation grid co-ordinates (x, y, z). I assume both are right handed so that \hat{u} \cross \hat{v} = \hat{w} and \hat{x} \cross \hat{y} = \hat{z}.

In the fidasim grid, the beam source is assumed to be at (x=0, y=0, z=0) and directed in the positive x direction. The simulation grid is then defined by nx,xmin,xmax and ny,ymin,ymax and nz,zmin,zmax which are all defined in the FIDASIM co-ordinate system (x, y, z).

Is 'origin' in the input file the location of the source in machine (u,v,w) co-ordinates?

Do the Tait-Bryan angles and 'origin' describe how to take a point defined in machine co-ordinates (u,v,w) to FIDASIM co-ordinates (x,y,z)? I.e alpha rotates about w to give (u',v',w') then beta rotates about v' to give (u'',v'',w''), and gamma about u'' to give (u''',v''',w''')? From there you would add 'origin' and you would arrive at the points location in FIDASIM (x,y,z) co-ordinates?

Or, do the Tait-Bryan angles describe how to go from FIDASIM co-ordinates (x,y,z) to machine co-ordinates (u,v,w)?

I assume you are aware that there are many ways to define the Tait-Bryan angles https://en.wikipedia.org/wiki/Euler_angles#Tait.E2.80.93Bryan_angles so, I think it would be great to specify exactly which convention you are using (I assume it is option 5 (intrinsic) on the wikipedia page)?

PS: I hate Euler/Tait-Bryan angles and how ambiguous they can be.

**Comment by shaunhaskey** [comment] 2016-04-11 17:05
@lstagner Just tagging you in this thread in case you never saw the new comment/question.

**Comment by lstagner** [comment] 2016-04-11 18:18
Yeah sorry for the late response

>There are two co-ordinate systems: Machine co-ordinates (u, v, w) and FIDASIM simulation grid co-ordinates (x, y, z). I assume both are right handed so that \hat{u} \cross \hat{v} = \hat{w} and \hat{x} \cross \hat{y} = \hat{z}.

yes
>In the fidasim grid, the beam source is assumed to be at (x=0, y=0, z=0) and directed in the positive x direction. The simulation grid is then defined by nx,xmin,xmax and ny,ymin,ymax and nz,zmin,zmax which are all defined in the FIDASIM co-ordinate system (x, y, z).

No. the beam source is not assumed to be at (0,0,0). 

>Is 'origin' in the input file the location of the source in machine (u,v,w) co-ordinates?

No, the origin can be anywhere you like in (u,v,w). I usually put it somewhere along the beam sightline

>Do the Tait-Bryan angles and 'origin' describe how to take a point defined in machine co-ordinates (u,v,w) to FIDASIM co-ordinates (x,y,z)? I.e alpha rotates about w to give (u',v',w') then beta rotates about v' to give (u'',v'',w''), and gamma about u'' to give (u''',v''',w''')? From there you would add 'origin' and you would arrive at the points location in FIDASIM (x,y,z) co-ordinates?
Or, do the Tait-Bryan angles describe how to go from FIDASIM co-ordinates (x,y,z) to machine co-ordinates (u,v,w)?

(x,y,z) -> (u,v,w)
The active rotation matrix `R` defined by the angles form a basis. So to go from xyz to uvw do is
```
uvw = xyz[1]*R[:,1] + xyz[2]*R[:,2] + xyz[3]*R[:,3] + origin
```
or 
```
uvw = R*xyz + origin
```

>I assume you are aware that there are many ways to define the Tait-Bryan angles https://en.wikipedia.org/wiki/Euler_angles#Tait.E2.80.93Bryan_angles so, I think it would be great to specify exactly which convention you are using (I assume it is option 5 (intrinsic) on the wikipedia page)?

Yes we are using an instrinsic active rotation matrix with order z-y'-x" . I will add the intrinsic to the docs

>PS: I hate Euler/Tait-Bryan angles and how ambiguous they can be.

They make more sense then Euler angles. It helped me to use my hand make sense of them.

1. Put your index finger of your right hand along the x/u axis
2. Rotate counter-clockwise about your thumb (alpha rotation)
3. Then rotate counter-clockwise about your middle finger (beta rotation)
4. Then rotate counter-clockwise about your index finger (gamma rotation)
5. Move your hand to the origin

Don't forget I made an IDL routine that makes it easy to define a beam aligned grid. 
http://d3denergetic.github.io/FIDASIM/sourcefile/beam_grid.pro.html
